In [47]:
# Using Jupyter notebooks with R in the classroom

<div style="display:flex;margin: 20px 10%">
<img src="http://i.imgur.com/BV0CdHZ.png?2" alt="ADSA logo" style="height:200px;vertical-align:middle"/>
</div>


ERROR: Error in parse(text = x, srcfile = src): <text>:3:1: unexpected '<'
2: 
3: <
   ^


In [2]:
#R allows for a plethora of different opperations such as:
#x + y
x <- 2
y <- 4

cat("x + y =", x + y, "\n")

#y - x
cat("y - x =", y - x, "\n")

#square root y
cat("sqrt(y) =", sqrt(y), "\n")

#y^(x + y)
cat("y^(x + y) = ", y ^ (x + y), "\n")


x + y = 6 
y - x = 2 
sqrt(y) = 2 
y^(x + y) =  4096 


In [12]:
# Assignments in R
# The c stands for combine and the idea is to store the list under a 
# given name refering to the data using the '<-' symbol
values <- c(1,2,3,4)
names <- c("Jake", "Jessica", "Rachel", "Alex")

In [13]:
#R allows accessing values within vectors by using square brackets []
values[3]
names[2]

[1] 3

[1] "Jessica"

In [14]:
#Additionally overwriting values is simple by 
values[3] <- 2
values

[1] 1 2 2 4

In [27]:
#There are several data types in R including logical, numeric, integer, character, and complex

"Logical:"
v <- TRUE
print(class(v))

"Numeric:"
v <- 1.5
print(class(v))

#Integers are numbers that can not have decimals in them. Putting an L forces them 
#to be stored as an integer.

"Integer:"
v <- 2L
print(class(v))

"Complex:"
v <- 3+2i
print(class(v))

"Character:"
v <- "Hey"
print(class(v))

[1] "Logical:"

[1] "logical"


[1] "Numeric:"

[1] "numeric"


[1] "Integer:"

[1] "integer"


[1] "Complex:"

[1] "complex"


[1] "Character:"

[1] "character"


In [30]:
#Lists are an R-Object type which can contain many different types of elements
#such as vectors, functions, and even lists inside
list1 <- list("Hello", c(1,2,3), 22, cos)
print(list1)

[[1]]
[1] "Hello"

[[2]]
[1] 1 2 3

[[3]]
[1] 22

[[4]]
function (x)  .Primitive("cos")



In [39]:
 #Matrixes are 2D data sets which can be created using vector input
m = matrix(c('a','b','c','d'), nrow = 2, ncol = 2, byrow = "TRUE")
print(m)

     [,1] [,2]
[1,] "a"  "b" 
[2,] "c"  "d" 


In [42]:
#Arrays alows more dimentions to the array
a <- array(m, dim = c(2,2,2))
print(a)

, , 1

     [,1] [,2]
[1,] "a"  "b" 
[2,] "c"  "d" 

, , 2

     [,1] [,2]
[1,] "a"  "b" 
[2,] "c"  "d" 



In [ ]:
# R's primary use however is using many data points rather than a few, and these 
# data points are usually stored in CSV files. CSV stands for comma seperated values and
# each line contains a row of values and each column is seperatedby a comma. The first line
# is assumed to be the labels for each column.